name: clean_arch
description: Clean Architecture with Test coverage of APIs and BLOC classes.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any
  path_provider: any
  intl: any
  logger: any
  flutter_screenutil: any
  lottie: any
  flutter_bloc: any
  uuid: any
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.3
  equatable: any
  json_annotation: any
  get_it: any

  dio: any
  shared_preferences: any
  rxdart: any
  firebase_core_platform_interface: any
  bloc_test: ^9.1.3
  flutter_riverpod: ^2.5.1

#  cupertino_icons: ^1.0.2
##  sqflite: ^2.0.2+1
#  path_provider: ^2.0.11
#  intl: ^0.17.0
#  logger: ^1.1.0
#  flutter_screenutil: ^5.5.3+2
#  lottie: ^1.3.0
#  flutter_bloc: ^8.0.1
#  uuid: ^3.0.6
#  firebase_core: ^1.17.1
#  cloud_firestore: ^4.0.0
#  equatable: ^2.0.3
#  json_annotation: ^4.5.0
#  get_it: ^7.2.0
#
#  dio: ^4.0.6
#  shared_preferences: ^2.0.15
#  rxdart: ^0.27.7
#  bloc_test: ^9.1.3

#dependency_overrides:
#  cloud_firestore: ^3.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.2.0
  build_runner: ^2.3.3
  mockito: ^5.3.2
  fake_cloud_firestore: ^2.4.1+1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # sourcefuse:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
